import { getSqlite } from '../db/connection';
import { analyzeKnowledgeCleanup } from './knowledge-cleanup';
import type { KnowledgeCleanupSuggestion } from '../../shared/types';

export interface DataCleanupPreview {
  suggestions: KnowledgeCleanupSuggestion[];
  totalItems: number;
  totalBytes: number;
}

export interface DataCleanupRunResult {
  applied: number;
  deletedRows: number;
  reclaimedBytesEstimate: number;
}

interface SuggestionRow {
  id: string;
  kind: string;
  payload_json: string | null;
  estimated_bytes: number;
}

interface CleanupPayload {
  category?: string;
  olderThan?: string;
  strategy?: string;
}

function parsePayload(raw: string | null): CleanupPayload {
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw) as CleanupPayload;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
}

function daysAgoIso(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export function previewDataCleanup(workspaceId: string): DataCleanupPreview {
  const suggestions = analyzeKnowledgeCleanup(workspaceId);
  return {
    suggestions,
    totalItems: suggestions.reduce((sum, s) => sum + s.itemCount, 0),
    totalBytes: suggestions.reduce((sum, s) => sum + s.estimatedBytes, 0),
  };
}

function cleanOrphanKbArtifacts(sqlite: ReturnType<typeof getSqlite>, workspaceId: string): number {
  let deleted = 0;
  deleted +=
    sqlite
      .prepare(
        `
    DELETE FROM kb_chunks
    WHERE workspace_id = ?
      AND NOT EXISTS (SELECT 1 FROM kb_pages p WHERE p.id = kb_chunks.page_id)
  `,
      )
      .run(workspaceId).changes ?? 0;
  deleted +=
    sqlite
      .prepare(
        `
    DELETE FROM kb_token_index
    WHERE workspace_id = ?
      AND NOT EXISTS (SELECT 1 FROM kb_pages p WHERE p.id = kb_token_index.page_id)
  `,
      )
      .run(workspaceId).changes ?? 0;
  deleted +=
    sqlite
      .prepare(
        `
    DELETE FROM kb_embedding_items
    WHERE workspace_id = ?
      AND page_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM kb_pages p WHERE p.id = kb_embedding_items.page_id)
  `,
      )
      .run(workspaceId).changes ?? 0;
  deleted +=
    sqlite
      .prepare(
        `
    DELETE FROM kb_embeddings
    WHERE workspace_id = ?
      AND NOT EXISTS (SELECT 1 FROM kb_embedding_items i WHERE i.id = kb_embeddings.item_id)
  `,
      )
      .run(workspaceId).changes ?? 0;
  return deleted;
}

function cleanArchivedKbPages(
  sqlite: ReturnType<typeof getSqlite>,
  workspaceId: string,
  olderThan: string,
): number {
  return (
    sqlite
      .prepare(
        `
    DELETE FROM kb_pages
    WHERE workspace_id = ?
      AND is_archived = 1
      AND is_pinned = 0
      AND updated_at < ?
  `,
      )
      .run(workspaceId, olderThan).changes ?? 0
  );
}

function cleanStaleAutoGeneratedKb(
  sqlite: ReturnType<typeof getSqlite>,
  workspaceId: string,
  olderThan: string,
): number {
  return (
    sqlite
      .prepare(
        `
    DELETE FROM kb_pages
    WHERE workspace_id = ?
      AND is_archived = 0
      AND is_pinned = 0
      AND kind IN ('auto-generated', 'agent-memory')
      AND updated_at < ?
      AND id NOT IN (
        SELECT target_id
        FROM knowledge_usage_stats
        WHERE workspace_id = ?
          AND target_kind = 'page'
          AND last_used_at >= ?
      )
  `,
      )
      .run(workspaceId, olderThan, workspaceId, olderThan).changes ?? 0
  );
}

function cleanDuplicateKbPages(
  sqlite: ReturnType<typeof getSqlite>,
  workspaceId: string,
  strategy: string | undefined,
): number {
  if (strategy === 'keepNewestByContent') {
    return (
      sqlite
        .prepare(
          `
      DELETE FROM kb_pages
      WHERE workspace_id = ?
        AND is_archived = 0
        AND is_pinned = 0
        AND id IN (
          WITH duplicate_groups AS (
            SELECT content_md AS key, count(*) AS count
            FROM kb_pages
            WHERE workspace_id = ?
              AND is_archived = 0
              AND is_pinned = 0
              AND length(coalesce(content_md, '')) > 240
            GROUP BY content_md
            HAVING count(*) > 1
          )
          SELECT p.id
          FROM kb_pages p
          JOIN duplicate_groups g ON g.key = p.content_md
          WHERE p.workspace_id = ?
            AND p.is_archived = 0
            AND p.is_pinned = 0
            AND p.id NOT IN (
              SELECT p2.id
              FROM kb_pages p2
              WHERE p2.workspace_id = p.workspace_id
                AND p2.content_md = p.content_md
              ORDER BY p2.updated_at DESC
              LIMIT 1
            )
        )
    `,
        )
        .run(workspaceId, workspaceId, workspaceId).changes ?? 0
    );
  }
  return (
    sqlite
      .prepare(
        `
    DELETE FROM kb_pages
    WHERE workspace_id = ?
      AND is_archived = 0
      AND is_pinned = 0
      AND id IN (
        WITH duplicate_groups AS (
          SELECT lower(trim(title)) AS key, count(*) AS count
          FROM kb_pages
          WHERE workspace_id = ?
            AND is_archived = 0
            AND is_pinned = 0
          GROUP BY lower(trim(title))
          HAVING count(*) > 1
        )
        SELECT p.id
        FROM kb_pages p
        JOIN duplicate_groups g ON g.key = lower(trim(p.title))
        WHERE p.workspace_id = ?
          AND p.is_archived = 0
          AND p.is_pinned = 0
          AND p.id NOT IN (
            SELECT p2.id
            FROM kb_pages p2
            WHERE p2.workspace_id = p.workspace_id
              AND lower(trim(p2.title)) = lower(trim(p.title))
            ORDER BY p2.updated_at DESC
            LIMIT 1
          )
      )
  `,
      )
      .run(workspaceId, workspaceId, workspaceId).changes ?? 0
  );
}

function cleanStaleEmbeddings(sqlite: ReturnType<typeof getSqlite>, workspaceId: string): number {
  return (
    sqlite
      .prepare(
        `
    DELETE FROM kb_embeddings
    WHERE workspace_id = ?
      AND (
        item_id NOT IN (SELECT id FROM kb_embedding_items WHERE workspace_id = ?)
        OR EXISTS (
          SELECT 1
          FROM kb_embedding_items i
          LEFT JOIN kb_pages p ON p.id = i.page_id
          WHERE i.id = kb_embeddings.item_id
            AND i.workspace_id = ?
            AND (
              kb_embeddings.updated_at < i.updated_at
              OR (p.id IS NOT NULL AND kb_embeddings.updated_at < p.updated_at)
            )
        )
      )
  `,
      )
      .run(workspaceId, workspaceId, workspaceId).changes ?? 0
  );
}

export function runDataCleanup(input: {
  workspaceId: string;
  suggestionIds: string[];
}): DataCleanupRunResult {
  const sqlite = getSqlite();
  if (input.suggestionIds.length === 0) {
    return { applied: 0, deletedRows: 0, reclaimedBytesEstimate: 0 };
  }
  const placeholders = input.suggestionIds.map(() => '?').join(',');
  const rows = sqlite
    .prepare(
      `
    SELECT id, kind, payload_json, estimated_bytes
    FROM cleanup_suggestions
    WHERE workspace_id = ?
      AND status = 'open'
      AND id IN (${placeholders})
  `,
    )
    .all(input.workspaceId, ...input.suggestionIds) as SuggestionRow[];

  const now = new Date().toISOString();
  const result = sqlite.transaction(() => {
    let deletedRows = 0;
    let reclaimedBytesEstimate = 0;
    for (const row of rows) {
      const payload = parsePayload(row.payload_json);
      const category = payload.category;
      if (category === 'orphanKbArtifacts') {
        deletedRows += cleanOrphanKbArtifacts(sqlite, input.workspaceId);
      } else if (category === 'archivedKbPages') {
        deletedRows += cleanArchivedKbPages(
          sqlite,
          input.workspaceId,
          payload.olderThan ?? daysAgoIso(30),
        );
      } else if (category === 'staleAutoGeneratedKb') {
        deletedRows += cleanStaleAutoGeneratedKb(
          sqlite,
          input.workspaceId,
          payload.olderThan ?? daysAgoIso(14),
        );
      } else if (category === 'duplicateKbPages') {
        deletedRows += cleanDuplicateKbPages(sqlite, input.workspaceId, payload.strategy);
      } else if (category === 'staleEmbeddings') {
        deletedRows += cleanStaleEmbeddings(sqlite, input.workspaceId);
      } else {
        continue;
      }
      reclaimedBytesEstimate += row.estimated_bytes;
      sqlite
        .prepare(
          `
        UPDATE cleanup_suggestions
        SET status = 'applied',
            decided_at = ?,
            applied_at = ?,
            updated_at = ?
        WHERE id = ?
      `,
        )
        .run(now, now, now, row.id);
    }
    return { applied: rows.length, deletedRows, reclaimedBytesEstimate };
  })();

  sqlite.pragma('wal_checkpoint(TRUNCATE)');
  return result;
}
