import { getSqlite } from '../db/connection';
import { cleanupSuggestionRepo } from '../db/repositories/knowledge-usage.repo';
import type { KnowledgeCleanupSuggestion } from '../../shared/types';

function daysAgoIso(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

function summarizeBytes(bytes: number): string {
  if (bytes >= 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  if (bytes >= 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${bytes} bytes`;
}

export function analyzeKnowledgeCleanup(workspaceId: string): KnowledgeCleanupSuggestion[] {
  const sqlite = getSqlite();
  const staleCutoff = daysAgoIso(14);
  const archivedCutoff = daysAgoIso(30);

  const orphanArtifacts = sqlite
    .prepare(
      `
    SELECT
      (
        SELECT count(*)
        FROM kb_chunks c
        WHERE c.workspace_id = ?
          AND NOT EXISTS (SELECT 1 FROM kb_pages p WHERE p.id = c.page_id)
      ) AS chunk_count,
      (
        SELECT coalesce(sum(c.size_compressed), 0)
        FROM kb_chunks c
        WHERE c.workspace_id = ?
          AND NOT EXISTS (SELECT 1 FROM kb_pages p WHERE p.id = c.page_id)
      ) AS chunk_bytes,
      (
        SELECT count(*)
        FROM kb_token_index t
        WHERE t.workspace_id = ?
          AND NOT EXISTS (SELECT 1 FROM kb_pages p WHERE p.id = t.page_id)
      ) AS token_count,
      (
        SELECT count(*)
        FROM kb_embedding_items i
        WHERE i.workspace_id = ?
          AND i.page_id IS NOT NULL
          AND NOT EXISTS (SELECT 1 FROM kb_pages p WHERE p.id = i.page_id)
      ) AS embedding_item_count
  `,
    )
    .get(workspaceId, workspaceId, workspaceId, workspaceId) as {
    chunk_count: number;
    chunk_bytes: number;
    token_count: number;
    embedding_item_count: number;
  };

  const orphanCount =
    orphanArtifacts.chunk_count +
    orphanArtifacts.token_count +
    orphanArtifacts.embedding_item_count;
  if (orphanCount > 0) {
    cleanupSuggestionRepo.upsertOpen({
      workspaceId,
      kind: 'kb_orphan',
      title: 'Artefatos órfãos da base de conhecimento',
      summary: `${orphanCount} artefato(s) de índice não têm mais página correspondente.`,
      reason:
        'Páginas foram removidas ou fontes foram reprocessadas; esses índices não ajudam mais a IA a responder.',
      payload: { category: 'orphanKbArtifacts' },
      estimatedBytes: orphanArtifacts.chunk_bytes,
      itemCount: orphanCount,
    });
  }

  const archived = sqlite
    .prepare(
      `
    SELECT count(*) AS count, coalesce(sum(length(coalesce(content_md, ''))), 0) AS bytes
    FROM kb_pages
    WHERE workspace_id = ?
      AND is_archived = 1
      AND is_pinned = 0
      AND updated_at < ?
  `,
    )
    .get(workspaceId, archivedCutoff) as { count: number; bytes: number };

  if (archived.count > 0) {
    cleanupSuggestionRepo.upsertOpen({
      workspaceId,
      kind: 'kb_stale',
      title: 'Páginas arquivadas antigas',
      summary: `${archived.count} página(s) arquivada(s) podem ser removidas após aprovação.`,
      reason:
        'Conteúdo arquivado e não fixado há mais de 30 dias raramente deve continuar ocupando índice e embeddings.',
      payload: { category: 'archivedKbPages', olderThan: archivedCutoff },
      estimatedBytes: archived.bytes,
      itemCount: archived.count,
    });
  }

  const staleUnused = sqlite
    .prepare(
      `
    SELECT count(*) AS count, coalesce(sum(length(coalesce(p.content_md, ''))), 0) AS bytes
    FROM kb_pages p
    LEFT JOIN knowledge_usage_stats u
      ON u.workspace_id = p.workspace_id
      AND u.target_kind = 'page'
      AND u.target_id = p.id
    WHERE p.workspace_id = ?
      AND p.is_archived = 0
      AND p.is_pinned = 0
      AND p.kind IN ('auto-generated', 'agent-memory')
      AND p.updated_at < ?
      AND (u.last_used_at IS NULL OR u.last_used_at < ?)
  `,
    )
    .get(workspaceId, staleCutoff, staleCutoff) as { count: number; bytes: number };

  if (staleUnused.count > 0) {
    cleanupSuggestionRepo.upsertOpen({
      workspaceId,
      kind: 'kb_stale',
      title: 'Memórias automáticas pouco usadas',
      summary: `${staleUnused.count} memória(s) automática(s) não foram usadas recentemente.`,
      reason:
        'A base cresceu com aprendizados que não aparecem nas buscas há mais de 14 dias; vale revisar antes de manter.',
      payload: { category: 'staleAutoGeneratedKb', olderThan: staleCutoff },
      estimatedBytes: staleUnused.bytes,
      itemCount: staleUnused.count,
    });
  }

  const duplicateTitles = sqlite
    .prepare(
      `
    WITH duplicate_groups AS (
      SELECT lower(trim(title)) AS key, count(*) AS count
      FROM kb_pages
      WHERE workspace_id = ?
        AND is_archived = 0
        AND is_pinned = 0
        AND title IS NOT NULL
      GROUP BY lower(trim(title))
      HAVING count(*) > 1
    ),
    duplicate_pages AS (
      SELECT p.id, length(coalesce(p.content_md, '')) AS bytes
      FROM kb_pages p
      JOIN duplicate_groups g ON g.key = lower(trim(p.title))
      WHERE p.workspace_id = ?
        AND p.is_archived = 0
        AND p.is_pinned = 0
        AND p.id NOT IN (
          SELECT p2.id
          FROM kb_pages p2
          WHERE p2.workspace_id = p.workspace_id
            AND lower(trim(p2.title)) = lower(trim(p.title))
          ORDER BY p2.updated_at DESC
          LIMIT 1
        )
    )
    SELECT count(*) AS count, coalesce(sum(bytes), 0) AS bytes FROM duplicate_pages
  `,
    )
    .get(workspaceId, workspaceId) as { count: number; bytes: number };

  if (duplicateTitles.count > 0) {
    cleanupSuggestionRepo.upsertOpen({
      workspaceId,
      kind: 'kb_duplicate',
      title: 'Páginas duplicadas por título',
      summary: `${duplicateTitles.count} página(s) parecem duplicadas por título e podem ser removidas mantendo a versão mais recente.`,
      reason:
        'Duplicatas competem no ranking RAG e podem fazer a IA citar uma versão antiga ou incoerente do mesmo conhecimento.',
      payload: { category: 'duplicateKbPages', strategy: 'keepNewestByTitle' },
      estimatedBytes: duplicateTitles.bytes,
      itemCount: duplicateTitles.count,
    });
  }

  const duplicateContent = sqlite
    .prepare(
      `
    WITH duplicate_groups AS (
      SELECT content_md AS key, count(*) AS count
      FROM kb_pages
      WHERE workspace_id = ?
        AND is_archived = 0
        AND is_pinned = 0
        AND length(coalesce(content_md, '')) > 240
      GROUP BY content_md
      HAVING count(*) > 1
    ),
    duplicate_pages AS (
      SELECT p.id, length(coalesce(p.content_md, '')) AS bytes
      FROM kb_pages p
      JOIN duplicate_groups g ON g.key = p.content_md
      WHERE p.workspace_id = ?
        AND p.is_archived = 0
        AND p.is_pinned = 0
        AND p.id NOT IN (
          SELECT p2.id
          FROM kb_pages p2
          WHERE p2.workspace_id = p.workspace_id
            AND p2.content_md = p.content_md
          ORDER BY p2.updated_at DESC
          LIMIT 1
        )
    )
    SELECT count(*) AS count, coalesce(sum(bytes), 0) AS bytes FROM duplicate_pages
  `,
    )
    .get(workspaceId, workspaceId) as { count: number; bytes: number };

  if (duplicateContent.count > 0) {
    cleanupSuggestionRepo.upsertOpen({
      workspaceId,
      kind: 'kb_duplicate',
      title: 'Páginas com conteúdo duplicado',
      summary: `${duplicateContent.count} página(s) têm o mesmo conteúdo markdown.`,
      reason:
        'Conteúdo idêntico aumenta custo de indexação e reduz diversidade dos resultados recuperados pela IA.',
      payload: { category: 'duplicateKbPages', strategy: 'keepNewestByContent' },
      estimatedBytes: duplicateContent.bytes,
      itemCount: duplicateContent.count,
    });
  }

  const staleEmbeddings = sqlite
    .prepare(
      `
    SELECT count(*) AS count, coalesce(sum(i.token_count * 4), 0) AS bytes
    FROM kb_embedding_items i
    LEFT JOIN kb_embeddings e ON e.item_id = i.id
    LEFT JOIN kb_pages p ON p.id = i.page_id
    WHERE i.workspace_id = ?
      AND (
        e.id IS NULL
        OR e.updated_at < i.updated_at
        OR (p.id IS NOT NULL AND e.updated_at < p.updated_at)
      )
  `,
    )
    .get(workspaceId) as { count: number; bytes: number };

  if (staleEmbeddings.count > 0) {
    cleanupSuggestionRepo.upsertOpen({
      workspaceId,
      kind: 'embedding_stale',
      title: 'Embeddings desatualizados',
      summary: `${staleEmbeddings.count} item(ns) sem embedding atual podem ser limpos para reindexação.`,
      reason:
        'Vetores antigos podem puxar contexto errado. Ao limpar, o próximo rebuild/indexação recria vetores consistentes.',
      payload: { category: 'staleEmbeddings' },
      estimatedBytes: staleEmbeddings.bytes,
      itemCount: staleEmbeddings.count,
    });
  }

  return cleanupSuggestionRepo.listOpen(workspaceId).map((s) => ({
    id: s.id,
    kind: s.kind,
    title: s.title,
    summary: s.summary,
    reason: s.reason,
    estimatedBytes: s.estimatedBytes,
    itemCount: s.itemCount,
    createdAt: s.createdAt,
    updatedAt: s.updatedAt,
  }));
}

export function cleanupSummaryText(suggestions: KnowledgeCleanupSuggestion[]): string {
  const totalItems = suggestions.reduce((sum, s) => sum + s.itemCount, 0);
  const totalBytes = suggestions.reduce((sum, s) => sum + s.estimatedBytes, 0);
  return `${totalItems} item(ns), aproximadamente ${summarizeBytes(totalBytes)}`;
}
